Repository HHS/TANF-app, pull requests merged in 2021-02, with the labels that each got.

#158 406 header focus fix
  tdrs-frontend/Dockerfile.dev
  tdrs-frontend/src/components/Alert/Alert.jsx
  tdrs-frontend/src/components/IdleTimer/IdleTimer.jsx
  tdrs-frontend/src/components/PrivateTemplate/PrivateTemplate.jsx
  tdrs-frontend/src/components/PrivateTemplate/PrivateTemplate.test.js
  tdrs-frontend/src/index.scss
Labels: QASP Review

#179 Update Design Guide
  docs/Design/Design-Guide.md
Labels: documentation

#168 Epics/398/backend/431 - 2
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/reports/migrations/0001_initial.py
  tdrs-backend/tdpservice/reports/migrations/0002_auto_20201215_1932.py
  tdrs-backend/tdpservice/reports/migrations/__init__.py
  tdrs-backend/tdpservice/reports/models.py
  tdrs-backend/tdpservice/reports/test/conftest.py
  tdrs-backend/tdpservice/reports/test/factories.py
  tdrs-backend/tdpservice/reports/test/test_models.py
Labels: QASP Review

#167 Issue/510 dotenv backend only
  .gitignore
  README.md
  tdrs-backend/.env.example
  tdrs-backend/README.md
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/development.py
  tdrs-backend/tdpservice/settings/env_vars/.env.local
  tdrs-backend/tdpservice/settings/local.py
  tdrs-backend/tdpservice/settings/test.py
  tdrs-backend/zap-scanner.sh
Labels: QASP Review

#183 431 part 3
  tdrs-backend/tdpservice/reports/errors.py
  tdrs-backend/tdpservice/reports/serializers.py
  tdrs-backend/tdpservice/reports/test/conftest.py
  tdrs-backend/tdpservice/reports/test/test_serializers.py
Labels: QASP Review

#175 Documentation/access controls ac 06
  docs/controls/access_control/ac-06.md
Labels: QASP Review, documentation

#180 Documentation/risk assessment ra 5
  docs/controls/risk_assessment/ra-05.md
  docs/controls/risk_assessment/ra-5-screenshots/Screen Shot 2021-01-29 at 3.05.42 PM.png
  docs/controls/risk_assessment/ra-5-screenshots/Screenshot_OWASP-ZAP-Scan_29012021.png
Labels: QASP Review, documentation

#181 Documentation/access controls ac 2
  docs/controls/access_control/ac-02.md
Labels: QASP Review, documentation

#198 Catchup hhs raft
  .github/pull_request_template.md
  docs/Design/Design-Guide.md
Labels: QASP Review
