Repository HHS/TANF-app, pull requests merged in 2024-08, with the labels that each got.

#533 v3.5.0.102 to prod
  docs/Sprint-Review/sprint-101-summary.md
  docs/Technical-Documentation/cloud-foundry-db-upgrade.md
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/apt.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/email/email_enums.py
  tdrs-backend/tdpservice/email/tasks.py
  tdrs-backend/tdpservice/email/templates/upcoming-submission-deadline.html
  tdrs-backend/tdpservice/email/test/test_upcoming_deadline_email.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/data/bad_trailer_2.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/transforms.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/scheduling/db_backup.py
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/admin/mixins.py
  tdrs-backend/tdpservice/search_indexes/admin/ssp.py
  tdrs-backend/tdpservice/search_indexes/admin/tanf.py
  tdrs-backend/tdpservice/search_indexes/admin/tribal.py
  tdrs-backend/tdpservice/search_indexes/migrations/0029_tanf_tribal_ssp_alter_verbose_names.py
  tdrs-backend/tdpservice/search_indexes/models/ssp.py
  tdrs-backend/tdpservice/search_indexes/models/tanf.py
  tdrs-backend/tdpservice/search_indexes/models/tribal.py
  tdrs-backend/tdpservice/search_indexes/templates/multiselectlistfilter.html
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  terraform/README.md
  terraform/create_backend_vars.sh
  terraform/create_tf_vars.sh
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: v3.5.0.102

#534 Release/v3.5.1 sprint 103
  .github/workflows/deploy-on-label.yml
  README.md
  Taskfile.yml
  commands.sh
  docs/How-We-Work/team-meetings.md
  docs/Security-Compliance/Security-Controls/cm-7-2/images/clamavcm7.PNG
  docs/Sprint-Review/sprint-102-summary.md
  docs/Sprint-Review/sprint-103-summary.md
  docs/Technical-Documentation/TDP-environments-README.md
  docs/Technical-Documentation/clean-and-reparse.md
  scripts/deploy-frontend.sh
  tdrs-backend/Dockerfile
  tdrs-backend/README.md
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/scheduling/management/BACKUP_README.md
  tdrs-backend/tdpservice/scheduling/management/__init__.py
  tdrs-backend/tdpservice/scheduling/management/commands/backup_db.py
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/scheduling/tasks.py
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/management/commands/tdp_search_index.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/docker-compose.local.yml
Labels: v3.5.1.103

#535 v3.5.1.103 to prod
  .github/workflows/deploy-on-label.yml
  README.md
  Taskfile.yml
  commands.sh
  docs/How-We-Work/team-meetings.md
  docs/Security-Compliance/Security-Controls/cm-7-2/images/clamavcm7.PNG
  docs/Sprint-Review/sprint-102-summary.md
  docs/Sprint-Review/sprint-103-summary.md
  docs/Technical-Documentation/TDP-environments-README.md
  docs/Technical-Documentation/clean-and-reparse.md
  scripts/deploy-frontend.sh
  tdrs-backend/Dockerfile
  tdrs-backend/README.md
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/scheduling/management/BACKUP_README.md
  tdrs-backend/tdpservice/scheduling/management/__init__.py
  tdrs-backend/tdpservice/scheduling/management/commands/backup_db.py
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/scheduling/tasks.py
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/management/commands/tdp_search_index.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/docker-compose.local.yml
Labels: v3.5.1.103

#538 Release/v3.5.2 sprint 104 update
  README.md
  docs/Technical-Documentation/TDP-environments-README.md
  scripts/deploy-backend.sh
  tdrs-backend/Dockerfile
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/test/test_email.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/util.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/templates/error_pages/500.html
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/api/login_redirect_oidc.py
  tdrs-backend/tdpservice/users/test/test_api/test_login.py
  tdrs-backend/tdpservice/users/test/test_auth.py
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
Labels: v.3.5.2.104

#539 v3.5.2.104 to prod
  README.md
  docs/Technical-Documentation/TDP-environments-README.md
  scripts/deploy-backend.sh
  tdrs-backend/Dockerfile
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/test/test_email.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/util.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/templates/error_pages/500.html
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/api/login_redirect_oidc.py
  tdrs-backend/tdpservice/users/test/test_api/test_login.py
  tdrs-backend/tdpservice/users/test/test_auth.py
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
Labels: v.3.5.2.104
