Repository HHS/TANF-app, pull requests merged in 2025-08, with the labels that each got.

#598 Patch Release v4.1.1
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/selectors/auth.js
Labels: v4.1.1

#599 Patch Release v4.1.2
  tdrs-backend/tdpservice/users/models.py
  tdrs-frontend/src/components/Reports/FRAReports.jsx
Labels: hotfix, v4.1.2

#600 v4.1.2 to prod
  tdrs-backend/tdpservice/users/models.py
  tdrs-frontend/src/components/Reports/FRAReports.jsx
Labels: hotfix, v4.1.2

#601 Release v4.2.0 Sprint 131
  Taskfile.yml
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/decoders.py
  tdrs-backend/tdpservice/parsers/management/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
Labels: v4.2.0.131

#602 Release v4.3.0
  .gitignore
  docs/Sprint-Review/sprint-128-summary.md
  docs/Sprint-Review/sprint-129-summary.md
  docs/Sprint-Review/sprint-130-summary.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/alertmanager/alertmanager.yml
  tdrs-backend/plg/grafana_views/generate_views.py
  tdrs-backend/plg/grafana_views/schema_fields.json
  tdrs-backend/tdpservice/fixtures/cypress/data_files.json
  tdrs-backend/tdpservice/fixtures/cypress/users.json
  tdrs-backend/tdpservice/parsers/admin.py
  tdrs-backend/tdpservice/parsers/base_parser.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/dataclasses.py
  tdrs-backend/tdpservice/parsers/duplicate_detectors.py
  tdrs-backend/tdpservice/parsers/error_generator.py
  tdrs-backend/tdpservice/parsers/fra_parser.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_manager.py
  tdrs-backend/tdpservice/parsers/tdr_parser.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/category2.py
  tdrs-backend/tdpservice/parsers/validators/category3.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category1.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category2.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category3.py
  tdrs-backend/tdpservice/parsers/validators/util.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/tdpservice/users/urls.py
  tdrs-backend/tdpservice/users/views.py
  tdrs-frontend/cypress.config.js
  tdrs-frontend/cypress/e2e/accounts/accounts.feature
  tdrs-frontend/cypress/e2e/accounts/accounts.js
  tdrs-frontend/cypress/e2e/common-steps/common-steps.js
  tdrs-frontend/cypress/e2e/common-steps/data_files.js
  tdrs-frontend/cypress/e2e/data-files/file_upload.feature
  tdrs-frontend/cypress/e2e/data-files/file_upload.js
  tdrs-frontend/cypress/e2e/data-files/submission_history.feature
  tdrs-frontend/cypress/e2e/data-files/submission_history.js
  tdrs-frontend/cypress/support/commands.js
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Reports/FRAReports.jsx
Labels: v4.3.0.132

#603 v4.2.0.131 and v4.3.0.132 to prod
  .gitignore
  Taskfile.yml
  docs/Sprint-Review/sprint-128-summary.md
  docs/Sprint-Review/sprint-129-summary.md
  docs/Sprint-Review/sprint-130-summary.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/alertmanager/alertmanager.yml
  tdrs-backend/plg/grafana_views/generate_views.py
  tdrs-backend/plg/grafana_views/schema_fields.json
  tdrs-backend/tdpservice/fixtures/cypress/data_files.json
  tdrs-backend/tdpservice/fixtures/cypress/users.json
  tdrs-backend/tdpservice/parsers/admin.py
  tdrs-backend/tdpservice/parsers/base_parser.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/dataclasses.py
  tdrs-backend/tdpservice/parsers/decoders.py
  tdrs-backend/tdpservice/parsers/duplicate_detectors.py
  tdrs-backend/tdpservice/parsers/error_generator.py
  tdrs-backend/tdpservice/parsers/fra_parser.py
  tdrs-backend/tdpservice/parsers/management/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_manager.py
  tdrs-backend/tdpservice/parsers/tdr_parser.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/category2.py
  tdrs-backend/tdpservice/parsers/validators/category3.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category1.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category2.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category3.py
  tdrs-backend/tdpservice/parsers/validators/util.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/tdpservice/users/urls.py
  tdrs-backend/tdpservice/users/views.py
  tdrs-frontend/cypress.config.js
  tdrs-frontend/cypress/e2e/accounts/accounts.feature
  tdrs-frontend/cypress/e2e/accounts/accounts.js
  tdrs-frontend/cypress/e2e/common-steps/common-steps.js
  tdrs-frontend/cypress/e2e/common-steps/data_files.js
  tdrs-frontend/cypress/e2e/data-files/file_upload.feature
  tdrs-frontend/cypress/e2e/data-files/file_upload.js
  tdrs-frontend/cypress/e2e/data-files/submission_history.feature
  tdrs-frontend/cypress/e2e/data-files/submission_history.js
  tdrs-frontend/cypress/support/commands.js
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Reports/FRAReports.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
Labels: v4.2.0.131, v4.3.0.132
