Repository HHS/TANF-app, pull requests merged in 2025-04, with the labels that each got.

#576 Patch FRA Excel Formula Field Parsing
  tdrs-backend/tdpservice/parsers/decoders.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/data/fra_formula_fields.xlsx
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: v3.8.1.122

#579 v3.8.2.123 to prod
  product-updates/knowledge-center/index.html
  tdrs-backend/tdpservice/stts/management/commands/data/tribes.csv
  tdrs-frontend/src/actions/fraReports.test.js
  tdrs-frontend/src/components/Reports/FRAReports.jsx
  tdrs-frontend/src/components/Reports/FRAReports.test.js
Labels: v3.8.2.123

#580 Release v3.8.3 Sprint 123
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/data_files/s3_client.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category1.py
  tdrs-frontend/src/actions/fraReports.js
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.test.js
  tdrs-frontend/src/components/SubmissionHistory/helpers.jsx
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: v3.8.3.123
